[package]
name = "rust-api-example"
version = "0.1.0"
authors = ["Maxime St-Pierre <me@maximest-pierre.me>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
diesel = { version = "1.4.0", features = ["sqlite"] }
dotenv = "0.10"